// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA10oGO_XizJwUoGFjZMddb9mOgOQRPu9U',
    appId: '1:890634428452:web:bf8ab0f7c6efa1f1e878b1',
    messagingSenderId: '890634428452',
    projectId: 'final-project-internncraft',
    authDomain: 'final-project-internncraft.firebaseapp.com',
    storageBucket: 'final-project-internncraft.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQDpSDMfC-MGRr5GPJtzPU1Dw98o6vMY',
    appId: '1:890634428452:android:82e8351351f3d60ae878b1',
    messagingSenderId: '890634428452',
    projectId: 'final-project-internncraft',
    storageBucket: 'final-project-internncraft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDezyvBq4KXZgb0xGhlbMljkmkkeOCVBIk',
    appId: '1:890634428452:ios:dbd07c853b5b5966e878b1',
    messagingSenderId: '890634428452',
    projectId: 'final-project-internncraft',
    storageBucket: 'final-project-internncraft.appspot.com',
    iosBundleId: 'com.example.finalProjectInternncraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDezyvBq4KXZgb0xGhlbMljkmkkeOCVBIk',
    appId: '1:890634428452:ios:dbd07c853b5b5966e878b1',
    messagingSenderId: '890634428452',
    projectId: 'final-project-internncraft',
    storageBucket: 'final-project-internncraft.appspot.com',
    iosBundleId: 'com.example.finalProjectInternncraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA10oGO_XizJwUoGFjZMddb9mOgOQRPu9U',
    appId: '1:890634428452:web:e6824dfadfff6015e878b1',
    messagingSenderId: '890634428452',
    projectId: 'final-project-internncraft',
    authDomain: 'final-project-internncraft.firebaseapp.com',
    storageBucket: 'final-project-internncraft.appspot.com',
  );
}
